/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.JOptionPane;
import perbankan.*;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.AbstractTableModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author jordan
 */


public class BankView extends javax.swing.JFrame {
    
    private Bank bank;
    private final DefaultTableModel tableModel;
    private int index;
    private int pointedIndex;

    /**
     * Creates new form NasabahView
     */
    public BankView() {   
        initComponents();
        this.index = 0;
        this.bank = new Bank();
        this.tableModel = (DefaultTableModel)tableNasabah.getModel();
        this.tableModel.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        labTitle = new javax.swing.JLabel();
        labNamaAwal = new javax.swing.JLabel();
        labNamaAkhir = new javax.swing.JLabel();
        formNamaAwal = new javax.swing.JTextField();
        formNamaAkhir = new javax.swing.JTextField();
        btnTambahNasabah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNasabah = new javax.swing.JTable();
        formSaldo = new javax.swing.JTextField();
        labSaldo = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSetor = new javax.swing.JButton();
        btnTarik = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        labTitle.setFont(new java.awt.Font("Nohemi", 0, 24)); // NOI18N
        labTitle.setText("Bank View");

        labNamaAwal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labNamaAwal.setText("Nama Awal");

        labNamaAkhir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labNamaAkhir.setText("Nama Akhir");

        formNamaAwal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        formNamaAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formNamaAwalActionPerformed(evt);
            }
        });

        formNamaAkhir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnTambahNasabah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTambahNasabah.setText("Tambah Nasabah");
        btnTambahNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahNasabahActionPerformed(evt);
            }
        });

        tableNasabah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Awal", "Nama Akhir", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableNasabah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BankView.this.mouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableNasabah);

        formSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labSaldo.setText("Saldo");

        btnHapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHapus.setText("Hapus Nasabah");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEdit.setText("Edit Nasabah");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSetor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSetor.setText("Setor");
        btnSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetorActionPerformed(evt);
            }
        });

        btnTarik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTarik.setText("Tarik");
        btnTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labNamaAwal)
                                        .addGap(48, 48, 48))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labNamaAkhir, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labSaldo, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(formNamaAkhir)
                                    .addComponent(formNamaAwal)
                                    .addComponent(formSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                                .addGap(138, 138, 138)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTambahNasabah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTarik, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formNamaAwal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labNamaAwal)
                                .addComponent(btnTambahNasabah)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formNamaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labNamaAkhir)
                            .addComponent(btnHapus)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSetor)
                        .addGap(18, 18, 18)
                        .addComponent(btnTarik)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit)
                    .addComponent(labSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formNamaAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formNamaAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formNamaAwalActionPerformed

    private void btnTambahNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahNasabahActionPerformed
        // catch form values and store to vars
        String namaAwal = formNamaAwal.getText();
        String namaAkhir = formNamaAkhir.getText();
        int saldo = formSaldo.getText().equals("") ? 0 : Integer.parseInt(formSaldo.getText()); 
        
        // formNama* shouldn't be empty
        if(!namaAwal.equals("") && !namaAkhir.equals("")) {
            // add nasabah object and set saldo
            this.bank.tambahNasabah(namaAwal, namaAkhir);
            this.bank.getNasabah(this.index).setTabungan(new Tabungan(saldo));
            
            // add nasabah attributes into table rows
            tableModel.addRow(new Object[]{bank.getNasabah(this.index).getNamaAwal(), 
                bank.getNasabah(this.index).getNamaAkhir(), 
                bank.getNasabah(this.index).getTabungan().getSaldo()});
            
            // increment nasabah count
            this.index++;
        } else {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi data");
        }
        
        formNamaAwal.setText("");
        formNamaAkhir.setText("");
        formSaldo.setText("");

    }//GEN-LAST:event_btnTambahNasabahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // delete row and delete object
        try {
            int rowIndex = tableNasabah.getSelectedRow();
            tableModel.removeRow(rowIndex);
            this.bank.hapusNasabah(rowIndex);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String namaAwal = formNamaAwal.getText();
        String namaAkhir = formNamaAkhir.getText();
        int saldo = Integer.parseInt(formSaldo.getText());
        
        try {
            this.bank.editNasabah(this.pointedIndex, namaAwal, namaAkhir);
            tableNasabah.setValueAt(namaAwal,this.pointedIndex, 0);
            tableNasabah.setValueAt(namaAkhir,this.pointedIndex, 1);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        // TODO add your handling code here:
        int row = tableNasabah.rowAtPoint(evt.getPoint());
        this.pointedIndex = tableNasabah.getSelectedRow();
        
        if(row >= 0) {
            String namaAwal = (String) tableModel.getValueAt(row, 0);
            String namaAkhir = (String) tableModel.getValueAt(row, 1);
            String saldo = tableModel.getValueAt(row, 2).toString();
            
            formNamaAwal.setText(namaAwal);
            formNamaAkhir.setText(namaAkhir);
            formSaldo.setText(saldo);
        }
    }//GEN-LAST:event_mouseClicked

    private void btnSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetorActionPerformed
        SetorView setorView = new SetorView();
        setorView.setVisible(true);
    }//GEN-LAST:event_btnSetorActionPerformed

    private void btnTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSetor;
    private javax.swing.JButton btnTambahNasabah;
    private javax.swing.JButton btnTarik;
    private javax.swing.JTextField formNamaAkhir;
    private javax.swing.JTextField formNamaAwal;
    private javax.swing.JTextField formSaldo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labNamaAkhir;
    private javax.swing.JLabel labNamaAwal;
    private javax.swing.JLabel labSaldo;
    private javax.swing.JLabel labTitle;
    private javax.swing.JTable tableNasabah;
    // End of variables declaration//GEN-END:variables
}
